from .config import *
from .model import *
BASE_CONFIG = SepReformerConfig(
    num_stages=4,
    num_spks=2,
    module_audio_enc=ModuleAudioEncConfig(
        in_channels=1,
        out_channels=256,
        kernel_size=16,
        stride=4,
        groups=1,
        bias=False,
    ),
    module_feature_projector=ModuleFeatureProjectorConfig(
        num_channels=256,
        in_channels=256,
        out_channels=128,
        kernel_size=1,
        bias=False,
    ),
    module_separator=ModuleSeparatorConfig(
        num_stages=4,
        relative_positional_encoding=RelativePositionalEncodingConfig(
            in_channels=128,
            num_heads=8,
            maxlen=2000,
            embed_v=False,
        ),
        enc_stage=EncStageConfig(
            global_blocks=GlobalBlocksConfig(
                in_channels=128,
                num_mha_heads=8,
                dropout_rate=0.05,
            ),
            local_blocks=LocalBlocksConfig(
                in_channels=128,
                kernel_size=65,
                dropout_rate=0.05,
            ),
            down_conv_layer=DownConvLayerConfig(
                in_channels=128,
                samp_kernel_size=5,
            ),
        ),
        spk_split_stage=SpkSplitStageConfig(
            in_channels=128,
            num_spks=2,
        ),
        simple_fusion=SimpleFusionConfig(
            out_channels=128,
        ),
        dec_stage=DecStageConfig(
            num_spks=2,
            global_blocks=GlobalBlocksConfig(
                in_channels=128,
                num_mha_heads=8,
                dropout_rate=0.05,
            ),
            local_blocks=LocalBlocksConfig(
                in_channels=128,
                kernel_size=65,
                dropout_rate=0.05,
            ),
            spk_attention=SpkAttentionConfig(
                in_channels=128,
                num_mha_heads=8,
                dropout_rate=0.05,
            ),
        ),
    ),
    module_output_layer=ModuleOutputLayerConfig(
        in_channels=256,
        out_channels=128,
        num_spks=2,
    ),
    module_audio_dec=ModuleAudioDecConfig(
        in_channels=256,
        out_channels=1,
        kernel_size=16,
        stride=4,
        bias=False,
    ),
)

SepReformer_Base = SepReformer(BASE_CONFIG)